/*
 * Renders data/normalised/report.md, the page the hand review of a scrape is done from
 * (docs/plans/normalise.md §7, ARCHITECTURE.md §13 "Full scrape reviewed by hand"). Pure:
 * the scrape date is passed in, so the same input always renders the same report.
 */
import type { CategoryResult } from './categories';
import { DEPARTMENT_WIDE_SHELF, type CleanProduct, type Exclusion } from './clean';
import type { Reconciled } from './departments';
import type { LoadIssue } from './load';

export interface ReportInput {
  scrapedAt: string;
  queued: number;
  products: CleanProduct[];
  loadIssues: LoadIssue[];
  exclusions: Exclusion[];
  departments: Reconciled;
  categories: Pick<CategoryResult, 'categories' | 'mixed' | 'unnamed'>;
  validationErrors: string[];
}

/** Longest list printed in full; the rest is summarised as a count. */
export const LIST_LIMIT = 20;

function table(headers: string[], rows: (string | number)[][]): string {
  const cell = (v: string | number) => String(v).replace(/\|/g, '\\|');
  return [
    `| ${headers.join(' | ')} |`,
    `| ${headers.map(() => '---').join(' | ')} |`,
    ...rows.map((row) => `| ${row.map(cell).join(' | ')} |`),
  ].join('\n');
}

/** `a, b, c … and 12 more` */
export function sample(items: string[], limit = LIST_LIMIT): string {
  const shown = items.slice(0, limit).join(', ');
  return items.length > limit ? `${shown} … and ${items.length - limit} more` : shown;
}

function byReason<R extends string>(items: { ean: string | null; reason: R }[]): Map<R, string[]> {
  const groups = new Map<R, string[]>();
  for (const item of items) {
    groups.set(item.reason, [...(groups.get(item.reason) ?? []), item.ean ?? '(unreadable)']);
  }
  return groups;
}

function reasonTable(items: { ean: string | null; reason: string }[]): string {
  if (items.length === 0) return 'None.';
  const rows = [...byReason(items)].map(([reason, eans]) => [reason, eans.length, sample(eans, 5)]);
  return table(['Reason', 'Products', 'Examples'], rows);
}

export function renderReport(input: ReportInput): string {
  const { products, departments, categories } = input;
  const names = new Map(departments.table.map((row) => [row.id, row.name]));
  const describe = (ids: string[]) =>
    sample(ids.map((id) => `${id} ${names.get(id) ?? ''}`.trim()));

  const perDepartment = new Map<string, { products: number; wide: number }>();
  for (const product of products) {
    const stats = perDepartment.get(product.departmentId) ?? { products: 0, wide: 0 };
    stats.products++;
    if (product.shelfId.endsWith(`:${DEPARTMENT_WIDE_SHELF}`)) stats.wide++;
    perDepartment.set(product.departmentId, stats);
  }
  const departmentRows = [...perDepartment]
    .sort((a, b) => b[1].products - a[1].products || a[0].localeCompare(b[0]))
    .map(([id, s]) => [
      id,
      names.get(id) ?? '',
      s.products,
      `${Math.round((100 * s.wide) / s.products)} %`,
    ]);

  return [
    '# Normalise report',
    '',
    `Scrape of ${input.scrapedAt}. Generated by \`scraper/normalise.ts\`; do not edit by hand.`,
    '',
    table(
      ['', 'Count'],
      [
        ['Listed', input.queued],
        ['Clean products', products.length],
        ['Excluded', input.exclusions.length],
        ['Not loaded', input.loadIssues.length],
        ['Shelf IDs', new Set(products.map((p) => p.shelfId)).size],
        ['Departments', departments.table.length],
        ['Categories', categories.categories.length],
      ],
    ),
    '',
    '## Validation',
    '',
    input.validationErrors.length === 0
      ? 'Passed.'
      : [
          `**${input.validationErrors.length} errors.**`,
          '',
          ...input.validationErrors.slice(0, LIST_LIMIT).map((e) => `- ${e}`),
          ...(input.validationErrors.length > LIST_LIMIT
            ? [`- … and ${input.validationErrors.length - LIST_LIMIT} more`]
            : []),
        ].join('\n'),
    '',
    '## Departments to review',
    '',
    `- Unreviewed (${departments.unreviewed.length}): ${describe(departments.unreviewed) || 'none'}`,
    `- New in this scrape (${departments.added.length}): ${describe(departments.added) || 'none'}`,
    `- In the table but not in this scrape (${departments.unused.length}): ${describe(departments.unused) || 'none'}`,
    '',
    '## Excluded products',
    '',
    reasonTable(input.exclusions),
    '',
    '## Not loaded',
    '',
    reasonTable(input.loadIssues),
    '',
    '## Categories',
    '',
    `- Mixed temperatures (${categories.mixed.length}): ${
      sample(
        categories.mixed.map(
          (m) =>
            `${m.path} (${m.votes.frozen} frozen / ${m.votes.chilled} chilled / ${m.votes.ambient} ambient)`,
        ),
      ) || 'none'
    }`,
    `- Named from their slug (${categories.unnamed.length}): ${sample(categories.unnamed) || 'none'}`,
    '',
    '## Products per department',
    '',
    'Department-only is the share on shelf `00`: the map routes those to the department area.',
    '',
    table(['Department', 'Name', 'Products', 'Department-only'], departmentRows),
    '',
  ].join('\n');
}
